# Application Documentation
:sectnumlevels: 4
:toclevels: 4
:sectnums: 4
:toc: left
:icons: font
:toc-title: Table of contents

*Last modified* : {docdate}

*Last editor* : link:https://github.com/noelvarga25[Noel Varga]

## Introduction
This document serves as the documentation for the application. It contains a general explanation of the application, its features, and how it is built.

Furthermore, the ins and outs of the application will be detailed in other documents such as each document will be linked to its detailed counterpart.

### Document Versioning

.Versioning reference
[cols="1,1,4,4"]
|===
| Version | Editor | Comments | Date

| 0.1 | Noel Varga | Creation of the document | 18/06/2022

|===

### Application Description

#### What is StayAlive?
StayAlive is a mobile application that allows public service call centers to notify healthcare providers, nursing assistants, and rescuers within 3 minutes of the patient via a mobile application in order to reduce response time.

Indeed, 50,000 people die from cardiac arrests. The survival rates are low, ranging between 5% and 10%, due to high response times. However, rapid response increases the survival rate by 72% in the case of a cardiac arrest, for example. StayAlive would be an application that enables emergency call centers like SAMU to notify healthcare providers, nursing assistants, and rescuers (who are our users) within 3 minutes of the victim. This would significantly reduce the time it takes to access initial medical care.

Furthermore, this would expedite the SAMU's response by utilizing the information gathered by the rescuer, who is also a user of our application. Ultimately, the goal is to notify individuals with medical qualifications during their routines, with the aim of saving lives.

#### Tech used
The SatyAlive application is built using React-Native. More precisly we are using:

- Metro v0.73.10
- React v18.2.0
- React-Native v0.71.7
- Typescript v4.8.4
- Jest v29.5.0

The application is built for Android and iOS compatibility.

### Rules

#### Editing

When editing this document, it is madatory to change the version number and the last editor. Furthermore, the date of the last modification must be changed as well.

#### Commits

When commiting changes to this document, it is mandatory to use the following syntax:

For any ADDition use the following syntax:

```sh
[ADD] Adding <functionnality>
```

When FIXing code, use the following syntax:

```sh
[FIX] Fixing <description>
```

In case you need to DELeting code or files, use the following syntax:

```sh
[DEL] Deleting <file_or_code_description>
```

When you would like to save your work ,please use the following syntax (Work In Progress):

```sh
[WIP] <description_of_the_ongoing_work>
```

## Target architecture

In this section we will discuss evrything related to to the application's architecture ranging from the diffrent use of folders to the diffrent components used.

### Folder structure

This section is dedicated to the folder structure of the application.

#### The main 'src' folder

Our application is built using React-Native. Therefore, the main folder of the application is the `src` folder. This folder contains all the code of the application.

Inside the `src` folder, we have three folders:

- LoginPage
- RegistrationPage
- Style

Inside the `LoginPage` folder, we currently have a file called `LoginPage.js`. This file contains the code of the login page.

Inside the `RegistrationPage` folder, we currently have three files called `RegistrationPage.js`, `RegistrationPage.test.js` and `textInputStayAlive.js`. The first file contains the code of the registration page, the second file contains the tests of the registration page and the third file contains the code of the text input fields used in the registration page.

Inside the `Style` folder, we currently have a file called `StayAliveStyle.js`. This file contains the code of the color style of our application.

Besides these folders, we can also find the `App.js` file. This is core file in our project since evrything will be routed threw this file.

#### Assets folder

The `assets` folder as it's name suggested, will hold all the necessary visual elements that will be used for the application.

From logos to backround images, this folder will only be used to store and hold images.

#### iOS folder

The `ios` folder is a standard folder that is automaticly generated by React-Native. This folder contains all the necessery elements in order to build the application for iOS.

On of the important elemnts of this folder is the `Podfile`. The `Podfile` is one of the most important files for the iOS build. It contains all the dependencies of the application and it regulates the ins and outs of the application settings.

Another crucial folder is the `Stayalive` folder. It is home to `AppDelegate.mm` file that is an essential element for the `google authentification`. Furthermore, the `Info.plist` file is also present. This is a mandatory file that houses all the information and credentials about the application. It is important because this file enables the authentification of the application on the App Store.

To finish off, it is also home to the Xcode folders. These two folders are important for Xcode to be able to open the project properly.

#### Android folder

As for the `ios` folder, in the same way the `android` folder is home to all the essential files that android needs in order to function properly.

The folder contains the graddle files required for the installation of dependecies for android. It also houses an `src` folder, with all the instructions for the emulator to build the app. This folder is much less utilized than the rest.

#### The documentation folder

The documentation folder also called `doc`, is home to all the documentation of the application. It contains the `StayAlive.adoc` file that is the main file of the documentation.

The plan for this folder is to contain all the detailed components documentation so developers will be able to understand the code and the application better.

It will also be hosting an asset folder. This asset folder will contain all the documents and images used in the documentation.

### Application architecture

Our application will be a visual interface. It will only house the 'front end' of our project. Evrything seen on the application will be stored in a dabase tha we will query to get all the necessary information.

In acordance to this, the user will require an internet access in order to use the application. This is important in order to be able to notify the user in case of an intervention.

As mentionned, the application will querry a database. The database will be responsible for the storage and security of the user's data.

## Constraints

## Warnings

## Contributors

|===
| Name | GitHub links | Role

| Martin LEBLANCS | link:https://github.com/MartinLeblancs[MartinLeblancs] | Mobile APP
| Noel VARGA      | link:https://github.com/noelvarga25[noelvarga25]    | Mobile APP
| Matthieu QUERU  | link:https://github.com/Matthieu33197[Matthieu33197]  | Web APP
| Bastien CANTET  | link:https://github.com/bastosbob[bastosbob]    | API
| Florian DAMIOT  | link:https://github.com/florianepitech[florianepitech] | API
|===
