name: Build Tests

on:
  workflow_run:
    workflows: ["Style Test"]
    types:
      - completed

jobs:
  ReactNative-JestTests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.SECRET_CODECOV }}
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
